version: '3'
services:
  cp-zookeeper:
    container_name: zk-vols
    ports:
      - 32181:32181
    networks:
      - kafka-local
    environment:
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_CLIENT_PORT: 32181
        JVMFLAGS: "-Xmx512m"
        KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf
            -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
            -Dzookeeper.allowSaslFailedClients=false
            -Dzookeeper.requireClientAuthScheme=sasl
    volumes:
        - './volumes/zk-data:/var/lib/zookeeper/data'
        - './volumes/zk-txn-logs:/var/lib/zookeeper/log'
        - ./configs/zookeeper.jaas.conf:/etc/kafka/zookeeper_server_jaas.conf
    image: 'confluentinc/cp-zookeeper:7.0.1'

  cp-kafka:
    container_name: kafka-vols
    networks:
      - kafka-local
    ports:
      - 9092:9092
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: cp-zookeeper:32181
        #- 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:39092'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
        KAFKA_LOG_RETENTION_HOURS: 2160 # 90 Days
        KAFKA_LOG_RENTENTION_BYTES: 524288000 # 500MB
        KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
        KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://cp-kafka:9092
        ZOOKEEPER_SASL_ENABLED: "false"
        KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
        KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
        KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
        KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
        - './volumes/kafka-data:/var/lib/kafka/data'
        - ./configs/kafka.jaas.conf:/etc/kafka/kafka_server_jaas.conf
    image: 'confluentinc/cp-kafka:7.0.1'
    depends_on:
      - cp-zookeeper
    
  kafka-ui:
    container_name: kafka-ui
    networks:
      - kafka-local
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8087:8080
    depends_on:
      - cp-zookeeper
      - cp-kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
  #    SERVER_SERVLET_CONTEXT_PATH: "/kafkaui"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: cp-kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: cp-zookeeper:32181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
  
  connect:
        image: confluentinc/cp-kafka-connect-base:7.0.0
        hostname: connect
        container_name: connect
        networks:
          - kafka-local
        ports:
          - 28083:28083
        links:
          - cp-kafka
          - cp-zookeeper
        environment:
          CONNECT_BOOTSTRAP_SERVERS: cp-kafka:9092
          CONNECT_REST_PORT: 28083
          CONNECT_GROUP_ID: "quickstart-avro"
          CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-avro-config"
          CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-avro-offsets"
          CONNECT_STATUS_STORAGE_TOPIC: "quickstart-avro-status"
          CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
          CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
          CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
          CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
          CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
          CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
          # Configure the Connect workers to use SASL/PLAIN.
          CONNECT_SASL_MECHANISM: PLAIN
          CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
          # JAAS
          CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
              username=\"admin\" \
              password=\"admin-secret\";"
          # producer
          CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
          CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
              username=\"admin\" \
              password=\"admin-secret\";"
          CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
          # consumer
          CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
          CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
              username=\"admin\" \
              password=\"admin-secret\";"
          CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
          # producer
          CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
          CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
          CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
              username=\"admin\" \
              password=\"admin-secret\";"
          # consumer
          CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
          CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
          CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
              username=\"admin\" \
              password=\"admin-secret\";"
        volumes:
          - ./conectors/confluentinc-kafka-connect-jdbc-10.3.3/lib:/etc/kafka-connect/jars
networks:
  kafka-local:
    